name: Post merge

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency: stream-s3-sqs-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  release:
    needs: tests
    name: Release
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master        
